---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=600
  when: ansible_os_family == 'Debian'

- name: Install authorization package dependencies
  ansible.builtin.package:
    name: '{{ authorization_packages }}'
    state: present
  become: true
  register: install_authorization_packages
  when: authorization_packages is defined
  tags:
    - install
    - apt
    - update_cache
