---
- name: Create files authorization
  become: true
  file:
    path: '{{ item.path }}'
    state: '{{ item.state }}'
    owner: '{{ item.owner }}'
  with_items: '{{ _authorization_create_files | default({}) }}'
  when: _authorization_create_files is defined
