---
- name: copy templates
  template:
    src: '{{ item.template }}'
    dest: '{{ item.path  }}'
  with_items: '{{ _authorization_templates | default({}) }}'
  when:
    - _authorization_templates is defined
