---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  vars:
    user: ubuntu
    authorization_user: '{{ user }}'
    authorization_key_public: '~/.ssh/id_rsa.pub'
    authorization_key_private: '~/.ssh/id_rsa'

  tasks:
    - name: 'Include ansible-role-authorization'
      include_role:
        name: 'ansible-role-authorization'
